### ISSUE TITLE
New incoming messages hidden on chromebook due to failure to scroll down.

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/monorepo#382] opened 2022-03-24 13:54 UTC
let's return to this once lazy loading is fixed in #386

**Comment by holmesworcester** [comment] 2022-03-24 13:56
If this bug turns out to be very specific to ChromeOS let's deprioritize it.

If it's a performance related issue then this is the right priority.

**Comment by siepra** [comment] 2022-03-31 12:36
Related to https://github.com/ZbayApp/monorepo/issues/386, fix will be included in https://github.com/ZbayApp/monorepo/pull/401

**Comment by holmesworcester** [comment] 2022-04-15 15:17
This isn't working in 1.4.1-alpha.5 for me. I still have to scroll down manually to see new messages.

**Comment by siepra** [comment] 2022-04-20 09:48
Duplicate of https://github.com/ZbayApp/monorepo/issues/231

**Closed by siepra** 2022-04-20 09:48 UTC
Labels: bug
